name: release-deb

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: |
          VERSION=$(echo $GITHUB_REF | cut --delimiter=/ -f 3)
          ID="whisper-cpp-small_$VERSION"
          
          echo "PKG_VERSION=$VERSION" >> $GITHUB_ENV
          echo "PKG_ID=$ID" >> $GITHUB_ENV

      - name: Install deps
        run: |
          sudo apt install -y --no-install-recommends intel-mkl

      - name: Build
        run: |
          cmake -S . -B build-release -D WHISPER_OPENBLAS=1
          cd build-release
          make
          cd ..

      - name: Create package tree
        run: |
          export ROOT=$PKG_ID/opt/project/whisper.cpp
          mkdir -p $ROOT/bin
          mkdir -p $ROOT/share
          mkdir -p $PKG_ID/DEBIAN
          
          cp build-release/bin/main $ROOT/bin/whisper 
          cp -r contrib/debian/control $PKG_ID/DEBIAN/
          
          echo "Version: $PKG_VERSION" >> $PKG_ID/DEBIAN/control
          echo "Git-Commit: $GITHUB_SHA" >> $PKG_ID/DEBIAN/control
          
          models/download-ggml-model.sh small
          build-release/bin/quantize models/ggml-small.bin \
            $ROOT/share/ggml-small-q5_1.bin q5_1

      - name: Create deb package
        run: |
          dpkg-deb --build --root-owner-group $PKG_ID
